### PR TITLE
Fix eslint version mismatch

### LINKED ISSUE #179: EsLint dependency version mismatch in atlas components
We currently have a problem building the UI packages.

From the above log I can see these errors that is related to a version mismatch of `eslint` library.

This is causing issues in these components:
- scxa-cell-type-wheel-experiment
- experiments-summary-panel
- species-summary-panel

```
All dependencies match the latest package versions :)
>> /Users/karoly/dev/gxa/atlas-web-single-cell/app/src/main/javascript/bundles/cell-type-wheel-heatmap$ rm -rf node_modules package-lock.json
>> /Users/karoly/dev/gxa/atlas-web-single-cell/app/src/main/javascript/bundles/cell-type-wheel-heatmap$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @ebi-gene-expression-group/scxa-cell-type-wheel-heatmap@1.0.0
npm ERR! Found: eslint@8.57.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^8.17.0" from the root project
npm ERR!   peer eslint@">= 8" from @ebi-gene-expression-group/eslint-config@3.5.1
npm ERR!   node_modules/@ebi-gene-expression-group/eslint-config
npm ERR!     dev @ebi-gene-expression-group/eslint-config@"^3.5.1" from the root project
npm ERR!   4 more (eslint-config-standard, eslint-plugin-import, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">=9" from eslint-plugin-cypress@4.0.0
npm ERR! node_modules/eslint-plugin-cypress
npm ERR!   peer eslint-plugin-cypress@">= 2" from @ebi-gene-expression-group/eslint-config@3.5.1
npm ERR!   node_modules/@ebi-gene-expression-group/eslint-config
npm ERR!     dev @ebi-gene-expression-group/eslint-config@"^3.5.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/karoly/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/karoly/.npm/_logs/2024-10-15T13_16_23_323Z-debug-0.log
>> /Users/karoly/dev/gxa/atlas-web-single-cell/app/src/main/javascript/bundles/cell-type-wheel-heatmap$ npm audit fix
npm ERR! code ENOLOCK
npm ERR! audit This command requires an existing lockfile.
npm ERR! audit Try creating one first with: npm i --package-lock-only
npm ERR! audit Original error: loadVirtual requires existing shrinkwrap file

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/karoly/.npm/_logs/2024-10-15T13_16_24_493Z-debug-0.log
```

### PR DESCRIPTION
**Pull request by lingyun1010**
@ebi-gene-expression-group/eslint-config versions caused errors while building npm packages in modules and cell-type-wheel-heatmap bundle, so we need to fix the package.json and building webpack bundles command to make sure we do not install nor update any old packages without keeping updating the root packages.

### CODE REVIEW

File: compile-front-end-packages.sh [hunk 1]
```diff
@@ -66,7 +66,6 @@ for MODULE_DIR in `ls`
 do
   pushd .
   cd $MODULE_DIR
-  update_npm_package
```
Comment (ke4) [inline compile-front-end-packages.sh:69]: Are you sure we don't need this `update` here?

**Review by ke4 — COMMENTED** [review]
I just added a question, as I am not sure if need that call or not...

File: compile-front-end-packages.sh (hunk 1 above)
Comment (lingyun1010) [reply compile-front-end-packages.sh:69]: Yea, actually, we are running this update_npm_package to update the front end component to the latest version without modifying manually, but this commond didn't consider version matching issues. In `module` directory, we only need to update the related "@ebi-gene-expression-group/atlas-homepage-cards" pakcage, but not "@ebi-gene-expression-group/eslint-config" and etc. In this way, we will not cause version dismatch issues under `MODULE_DIR`. And of course, if we would like to update "@ebi-gene-expression-group/atlas-homepage-cards" pakcage, we need to do that manually and keep an eye on the version compability issues.

Comment (lingyun1010) [reply compile-front-end-packages.sh:69]: I have another comment here, I could not remember why we had this module directory ( but I think it had some reasons), but we may also be able to move all module packages as published npm package as other front end components, so we don't have to build any local front end component under `atlas-web-single-cell`, in this way, we would not have any package version issues while building bundles, as we should sort it out in the front end before integrating it to the back end. I suggest to do some refactoring not only for the [decoupling experiment page](https://github.com/ebi-gene-expression-group/atlas-components/issues/171) issue, but also the module directory.

Comment (ke4) [reply compile-front-end-packages.sh:69]: OK. If it is simplifying how to build the app then I am all in favour.

**Review by ke4 — APPROVED** [review]
LGTM
