### PR TITLE
bugfix/update-cell-type-marker-genes-endpoint-to-accept-slash-in-the-celltype

### LINKED ISSUE #467: Add url decoder for cell type heatmap search bug fix testing and fix in the current develop branch if it is broken
This is the reference PR  - [Bug fix](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/355).

The above PR has been merged to develop and closed. But during so many changes in the development Branch, the fix code has been removed or something messed up with the fix. So, the fix is not working.

Target: We need to verify the bugfix code in the current development branch and test. 
          
If the fix is not working as expected, fix it. Follow the below steps for the clean fix after testing (only if the fix already not exists in the code base).

1. Create a new branch from the current Develop branch
2. Cherry pick bugfix code from the above PR
3. Test the branch and if all is good, create a PR

### PR DESCRIPTION
**Pull request by upendrakumbham**
Add Base64 decoder to decode cell type which is received by the frontend

In the frontend celltypewheel when we clicked on cell type with / value, the backend did not accept that URI, so we added encodeURIComponent(btoa) functions at the frontend to do Base64 encode of cell type as part of URI to accept '/' by the tomcat and API endpoint(/json/cell-type-marker-genes/{cellType})

### CODE REVIEW

File: app/src/main/java/uk/ac/ebi/atlas/search/metadata/JsonMultiexperimentCellTypeMarkerGenesController.java [hunk 1]
```diff
@@ -28,17 +31,26 @@ public JsonMultiexperimentCellTypeMarkerGenesController(
...
+                                        getDecodedCellType(cellType))));
+    }
+
+    private static @NotNull String getDecodedCellType(@NotNull String cellType) {
+        if (cellType == null || cellType.trim().isEmpty()) {
+            throw new IllegalArgumentException("Input cellType cannot be null or empty");
+        }
+
+        byte[] decodedBytes = Base64.getDecoder().decode(cellType);
+        return new String(decodedBytes, StandardCharsets.UTF_8);
```
Comment (ke4) [inline app/src/main/java/uk/ac/ebi/atlas/search/metadata/JsonMultiexperimentCellTypeMarkerGenesController.java]: inline variable as we are not using it later
```suggestion
        return new String(Base64.getDecoder().decode(cellType), StandardCharsets.UTF_8);
```

File: app/src/main/java/uk/ac/ebi/atlas/search/metadata/JsonMultiexperimentCellTypeMarkerGenesController.java [hunk 2]
```diff
@@ -28,17 +31,26 @@ public JsonMultiexperimentCellTypeMarkerGenesController(
...
                                 multiexperimentCellTypeMarkerGenesService.getCellTypeMarkerGeneProfile(
-                                        URLDecoder.decode(cellType, StandardCharsets.UTF_8)) :
+                                        getDecodedCellType(cellType)) :
                                 multiexperimentCellTypeMarkerGenesService.getCellTypeMarkerGeneProfile(
                                         ImmutableSet.copyOf(experimentAccessions),
-                                        URLDecoder.decode(cellType, StandardCharsets.UTF_8))));
+                                        getDecodedCellType(cellType))));
+    }
+
+    private static @NotNull String getDecodedCellType(@NotNull String cellType) {
```
Comment (ke4) [inline app/src/main/java/uk/ac/ebi/atlas/search/metadata/JsonMultiexperimentCellTypeMarkerGenesController.java]: Do we need the @NotNull annotations here? I know that IntelliJ is adding that to your code when you probably extracted out from the `getCellTypeMarkerGenes` method. But do we really need them?
If no, then we can remove them and with that decrease the dependency on JetBrains.

File: app/src/test/java/uk/ac/ebi/atlas/search/metadata/JsonMultiexperimentCellTypeMarkerGenesControllerWIT.java [hunk 3]
```diff
@@ -87,10 +87,19 @@ void shouldReturnAValidJsonPayloadForACellTypeContainingAForwardSlash() throws E
...
                 .andExpect(jsonPath("$", is(empty())));
     }
+
+    private static String getEncodedCellType(String cellType) {
+        if (cellType == null) {
+            throw new IllegalArgumentException("cellType cannot be null");
+        }
+
+        byte[] cellTypeBytes = cellType.getBytes(StandardCharsets.UTF_8);
+        return Base64.getEncoder().encodeToString(cellTypeBytes);
```
Comment (ke4) [inline app/src/test/java/uk/ac/ebi/atlas/search/metadata/JsonMultiexperimentCellTypeMarkerGenesControllerWIT.java]:
```suggestion
        return Base64.getEncoder().encodeToString(cellType.getBytes(StandardCharsets.UTF_8));
```

**Review by ke4 — CHANGES_REQUESTED** [review]
Thanks for your work!
Just tiny suggestions.
Thanks

**Review by ke4 — DISMISSED** [review]
LGTM! Thanks for your work! 👍

**Review by ke4 — DISMISSED** [review]
Good to go.
Thanks

**Review by ke4 — APPROVED** [review]
Fine with me, I am going to approve it.
All I ask is to add [Bugfix] prefix when you merge it to the merge's commit message.
Thanks
